### ISSUE TITLE
plugins page 404

### ISSUE THREAD

**Issue by khashashin** [nb557/plugins#4]
the plugins page does not work

**Comment by LinuxFlow1** [comment]
Не работает плагин выдает ошибку 404, есть ли решение проблемы
![Uploading Screenshot_2024-06-11-09-07-21-24_63ed6105256e5605035b105224809426.jpg…]()

**Comment by LinuxFlow1** [comment]
![Screenshot_2024-06-11-09-07-32-34_63ed6105256e5605035b105224809426](https://github.com/nb557/plugins/assets/163661095/7c4318f7-6b4b-43fe-9572-e30afb82735f)

**Comment by TopperBG** [comment]
Попробуй так:
https://raw.githubusercontent.com/nb557/plugins/main/online_mod.js

**Comment by LinuxFlow1** [comment]
Огромное спасибо помогло

вт, 11 июн. 2024 г., 09:21 TopperBG ***@***.***>:

**Comment by khashashin** [comment]
The right link actually was [https://nb557.github.io/plugins/online_mod.js](https://nb557.github.io/plugins/online_mod.js)
