### ISSUE TITLE
Плагин Онлайн - управление списком серий

### ISSUE THREAD

**Issue by GitUser200607** [nb557/plugins#6]
Не знаю, где и кому писать, но после какого-то из обновлений (то ли лампы, то ли online-плагина), пропал список серий. Теперь, если нажать на пульте кнопку ВНИЗ, открывается не список серий, а какой-то раздел "Смотреть далее".
Где копать, чтобы вернуть список серий сериала?

**Comment by nb557** [comment]
![playlist1](https://github.com/user-attachments/assets/1b4b4213-387f-49f8-b749-c642e0df5765)
![playlist2](https://github.com/user-attachments/assets/5fbb8124-d702-4ad0-8089-8d9baf62bc72)
Вроде как кнопка на месте, а на счет того что показывается при нажатия ВНИЗ, то это пиши в саму лампу https://github.com/yumata/lampa-source
